name: My First CI

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Explore the runner
        run: |
          echo "Hello from GitHub Actions"
        echo "Current directory:"
        pwd
        echo "Files in repository:"
        ls -la
        echo "Node Version:"
        node --version

      - name: Show Node version
        run: node --version
