name: My First CI

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: echo "Linting code"

  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: echo "Running unit tests"

  build:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: echo "Building application"
