name: Node CI

env:
  NODE_VERSION: 24
  APP_NAME: npm-ci-demo
  DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check secret
        run: |
          echo "The secret was loaded."
          echo "Secret length: ${#DEMO_SECRET}"
          
      - name: Use secret
        run: echo "Secret exists"
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}
          cache: npm
      - name: Show environment variables
        run: |
          echo "App name: $APP_NAME"
          echo "Default Node version: $NODE_VERSION"          

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint


  unit-test:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20,22,24]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node${{matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  build:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/

  verify-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: downloaded-build

      - name: Show downloaded files
        run: |
          echo "Downloaded artifact contents:"
          ls -la downloaded-build
